// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simpop
List simpop(double logFM, List dat, List set, int out);
RcppExport SEXP _mse_simpop(SEXP logFMSEXP, SEXP datSEXP, SEXP setSEXP, SEXP outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type logFM(logFMSEXP);
    Rcpp::traits::input_parameter< List >::type dat(datSEXP);
    Rcpp::traits::input_parameter< List >::type set(setSEXP);
    Rcpp::traits::input_parameter< int >::type out(outSEXP);
    rcpp_result_gen = Rcpp::wrap(simpop(logFM, dat, set, out));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mse_simpop", (DL_FUNC) &_mse_simpop, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
